version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-thomasfrancois-cv
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-thomasfrancois-cv.rule=Host(`thomasfrancois.net`)"
      - "traefik.http.routers.web-thomasfrancois-cv.entrypoints=websecure"
      - "traefik.http.routers.web-thomasfrancois-cv.tls.certresolver=myresolver"
    networks:
      - traefik

networks:
  traefik:
    external: true